import { jsPDF } from 'jspdf'
import { triggerDownload } from './exportImport'

export interface Charity {
  id: string
  name: string
  description: string
  category: string
  address: string
  website?: string
}

export interface CharityDonation {
  id: string
  charityId: string
  charityName: string
  donorAddress: string
  wasteItemIds: number[]
  tokenAmount: bigint
  timestamp: number
  receiptNumber: string
}

// Curated list of registered charities
export const REGISTERED_CHARITIES: Charity[] = [
  {
    id: 'eco-foundation',
    name: 'Eco Foundation',
    description: 'Promoting sustainable recycling in underserved communities.',
    category: 'Environment',
    address: 'GAECO123FOUNDATION',
    website: 'https://ecofoundation.example',
  },
  {
    id: 'green-schools',
    name: 'Green Schools Initiative',
    description: 'Funding recycling programs in public schools.',
    category: 'Education',
    address: 'GGREENSCHOOLS456',
    website: 'https://greenschools.example',
  },
  {
    id: 'ocean-cleanup',
    name: 'Ocean Cleanup Alliance',
    description: 'Removing plastic waste from oceans and coastlines.',
    category: 'Environment',
    address: 'GOCEAN789CLEANUP',
    website: 'https://oceancleanup.example',
  },
  {
    id: 'community-recyclers',
    name: 'Community Recyclers Network',
    description: 'Supporting local recycling cooperatives worldwide.',
    category: 'Community',
    address: 'GCOMMUNITY012NET',
  },
]

const LS_KEY = (address: string) => `scavngr_charity_donations_${address}`

function load(address: string): CharityDonation[] {
  try {
    const raw = localStorage.getItem(LS_KEY(address))
    if (!raw) return []
    const parsed = JSON.parse(raw) as Array<Omit<CharityDonation, 'tokenAmount'> & { tokenAmount: string }>
    return parsed.map((d) => ({ ...d, tokenAmount: BigInt(d.tokenAmount) }))
  } catch {
    return []
  }
}

function save(address: string, donations: CharityDonation[]): void {
  const serialisable = donations.map((d) => ({ ...d, tokenAmount: d.tokenAmount.toString() }))
  localStorage.setItem(LS_KEY(address), JSON.stringify(serialisable))
}

export class CharityStorage {
  private address: string

  constructor(address: string) {
    this.address = address
  }

  getAll(): CharityDonation[] {
    return load(this.address)
  }

  record(donation: Omit<CharityDonation, 'id' | 'receiptNumber' | 'timestamp'>): CharityDonation {
    const now = Date.now()
    const entry: CharityDonation = {
      ...donation,
      id: `don_${now}`,
      timestamp: now,
      receiptNumber: `RCP-${now.toString(36).toUpperCase()}`,
    }
    save(this.address, [entry, ...load(this.address)])
    return entry
  }
}

export function generateDonationReceipt(donation: CharityDonation, donorAddress: string): void {
  const doc = new jsPDF()
  const m = 14
  let y = 20

  doc.setFontSize(20)
  doc.text('Donation Tax Receipt', m, y)
  y += 12

  doc.setFontSize(11)
  doc.setTextColor(100)
  doc.text(`Receipt No: ${donation.receiptNumber}`, m, y)
  y += 7
  doc.text(`Date: ${new Date(donation.timestamp).toLocaleString()}`, m, y)
  y += 14

  doc.setTextColor(0)
  doc.setFontSize(13)
  doc.text('Donor', m, y)
  y += 8
  doc.setFontSize(11)
  doc.text(`Address: ${donorAddress}`, m, y)
  y += 14

  doc.setFontSize(13)
  doc.text('Recipient Charity', m, y)
  y += 8
  doc.setFontSize(11)
  doc.text(`Name: ${donation.charityName}`, m, y)
  y += 7
  doc.text(`Charity ID: ${donation.charityId}`, m, y)
  y += 14

  doc.setFontSize(13)
  doc.text('Donation Details', m, y)
  y += 8
  doc.setFontSize(11)
  doc.text(`Token Amount: ${donation.tokenAmount.toLocaleString()} tokens`, m, y)
  y += 7
  if (donation.wasteItemIds.length > 0) {
    doc.text(`Waste Items: #${donation.wasteItemIds.join(', #')}`, m, y)
    y += 7
  }
  y += 7

  doc.setFontSize(9)
  doc.setTextColor(130)
  doc.text('This receipt is generated by Scavngr and may be used for tax deduction purposes.', m, y)
  y += 5
  doc.text(`Generated: ${new Date().toLocaleString()}`, m, y)

  const blob = doc.output('blob')
  triggerDownload(blob, `receipt-${donation.receiptNumber}.pdf`)
}
